= Templates
:author: Harmen Weber
:email: harmen.weber@gmail.com
:keywords: asciidoc-templates

== Simple Letter

I use this template as a starting point when writing letters in AsciiDoc.
I just copy the `templates/simple-letter.adoc`, rename it and start typing my letter.

Below is the PDF of the template.
It was generated using the xref:themes.adoc#_nord[Nord] theme.

++++
<iframe src="_attachments/simple-letter.pdf" height="400px" style="margin: 0 auto; display:block;"></iframe>
++++

The positioning of the addressee paragraph is tricky.
Unfortunately, Asciidoctor PDF does not allow absolute positioning of paragraphs or blocks.
At least not to my knowledge.
The best thing I can currently offer is the following:

To change the vertical position of the addressee paragraph, you first update the sender paragraph to your needs.
Once the height of the sender paragraph is clear, you can change the height of the transparent spacer image between the sender paragraph and the addressee paragraph.
Adjust the height of the transparent spacer image until the addressee paragraph sits nicely in the addressee window of your envelopes.

.Vertical addressee positioning
image::vertical-positioning-of-addressee-in-simple-letter.drawio.svg[]

To change the horizontal position of the addressee paragraph, you change the width of the columns of the table that wraps the addressee paragraph.

.Horizontal addressee positioning
image::horizontal-positioning-of-addressee-in-simple-letter.drawio.svg[]

Make sure you change the path to the signature file to point to your signature file.

== Résumé / Curriculum Vitae (CV)

This is a template for a simple résumé.
If you are into fancy looking résumés, this template here is not for you.
AsciiDoc is not a page layout design tool.
Use something else for fancy layouts.

The template is located at `templates/cv.adoc`.

Below is the PDF of the template.
It was generated using the xref:themes.adoc#_nord[Nord] theme.

++++
<iframe src="_attachments/cv.pdf" height="400px" style="margin: 0 auto; display:block;"></iframe>
++++

== Simple Article

I use the simple article template

* as a reference on how to do certain things in AsciiDoc like callouts or tables
* to test the looks of things when working with xref:themes.adoc[].

The template is located at `templates/simple-article.adoc`.

Below is the PDF of the template.
It was generated using the xref:themes.adoc#_nord[Nord] theme.

++++
<iframe src="_attachments/simple-article.pdf" height="400px" style="margin: 0 auto; display:block;"></iframe>
++++

== Folder Cover

I used to keep hard copies of documents in folders.
In these folders, I grouped the documents by topic.
For every topic, I created a cover page.
That allowed me to quickly crawl through my folders in search for a specific topic.

Although I'm not using it anymore, I still have my simple folder cover template.
It is located at `templates/folder-cover.adoc`.

Here is the PDF of the template.
It was generated using the xref:themes.adoc#_nord[Nord] theme.

++++
<iframe src="_attachments/folder-cover.pdf" height="400px" style="margin: 0 auto; display:block;"></iframe>
++++