= Themes
:author: Harmen Weber
:email: harmen.weber@gmail.com
:keywords: asciidoc-templates

== Nord

I love the https://www.nordtheme.com[Nord theme].
Unfortunately, I'm terrible at adopting themes.
Nevertheless, I spent a bit of effort to make my documents use the colors of the Nord theme.
The theme is located at link:{url-repo}/themes/nord-theme.yml[themes/nord-theme.yml].

=== Usage

The simplest way to use the theme, is to call the script link:{url-repo}/scripts/create-pdf-with-nord-theme.sh[scripts/create-pdf-with-nord-theme.sh] and pass your AsciiDoc file as argument to it.

[source,shell]
----
./scripts/create-pdf-with-nord-theme.sh your-article.adoc
----

Read xref:scripts.adoc[] and take a look at the source of the script to learn more about the script.

=== Features

The theme extends the theme _default-with-fallback-font_ with colors and styling that kinda match the Nord theme.

The theme uses the font Noto Sans for regular text and Jetbrains Mono for code.

The theme defines sixteen roles named according to the sixteen colors in the Nord color palette: `nord0`, `nord1`, ... until ..., `nord15`.
Use the roles to customize the font color of paragraphs or inline phrases.
For paragraphs, prepend the entire paragraph with `[.nord12]`.
For inline phrases, wrap your inline phrase as follows: `[.nord12]\#your inline phrase#`.